spring:
  data:
    mongodb:
      uri: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${SPRING_DATA_MONGODB_PASSWORD}@${MONGO_HOST}:27017/reactive_database?authSource=admin
  kafka:
    consumer: #different to producer
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER} #variable aca enviroment
      group-id: debitCardGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: transferenceConfirmation:com.dev.ms_debitcard.kafka.TransferenceConfirmation

server:
  port: 8060
client:
  service:
    uri: ${WEBCLIENT_BASE_URL}