spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations
server:
  port: 8888

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  instance:
    hostname: discovery-server
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
